<a href="https://colab.research.google.com/github/esineyildiz/deep-learning-mike-cohen/blob/main/5_16_Vector_and_matrix_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libs
import numpy as np
import torch

In [ ]:
# create a vector
nv = np.array([ [1, 2, 3,4] ]) # first set of sqr bracets to indicate that
# we want to input an array!!! second set of [] is to INDICATE THE FIRST ROW
print(nv), print(' ')

# np.transpose(nv) another method
 # transpose it
print(nv.T), print(' ') # you are not acc transposing here, you ar eprinting
# the original array, transposed

# transpose the transpose
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [ ]:
# repeat for a matrix
nM = np.array([ [1,2,3,4],[5,6,7,8] ])
print(nM), print(' ')

# transpose it
print(nM.T), print(' ')

# transpose the transpose
nMT = nM.T
print(nMT.T)


[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# better visalization
nM = np.array([ [1,2,3,4],
                [5,6,7,8]
                ])
print(nM)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# same operation in pyTorch
# in this case numPy and PyTorch are almost the same
# but in other cases the syntaxes are different
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transposed
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [ ]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],
                [5,6,7,8]
                ])
# transpose it
print(tM.T), print(' ')

# transpose the transposed
tMT = tM.T
print(tMT.T)

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# examine data types
print(f'Varaible nv is of type{type(nv)}')
print(f'Varaible nM is of type{type(nM)}')
print(f'Varaible tv is of type{type(tv)}')
print(f'Varaible tM is of type{type(tM)}')

Varaible nv is of type<class 'numpy.ndarray'>
Varaible nM is of type<class 'numpy.ndarray'>
Varaible tv is of type<class 'torch.Tensor'>
Varaible tM is of type<class 'torch.Tensor'>
