<a href="https://colab.research.google.com/github/esineyildiz/deep-learning-mike-cohen/blob/main/5_18_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import numpy as np
import torch

In [ ]:
# using numpy

# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplication...
# np.round(MxN,  2) comma 2 will round to two sginificant
# digits after decimal point

print(np.round(A@B ,2 )), print(' ') # shortcut
# A@B is the same thing as
# np.matmul(A,B)

#print(np.round(A@C ,2)), print(' ') # matmul is not defined

#print(np.round(B@C ,2)), print(' ') # matmul is not defined

print(np.round(C.T@A,  2))

[[ 1.39 -0.86  1.08  0.65 -2.65]
 [ 0.52 -1.48  1.72  1.08 -2.69]
 [-0.15 -0.1  -0.    0.2   0.23]]
 
[[-1.67  0.65  0.17  0.68]
 [ 1.1  -1.96  0.    1.47]
 [ 5.64 -2.23 -0.71 -2.07]
 [ 2.4  -2.85  0.15  1.1 ]
 [-2.12  0.93  0.19  0.75]
 [-1.39  0.92  0.14  0.06]
 [ 3.4  -1.06 -0.43 -1.63]]


In [ ]:
 # Usiing pytorch
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1,dtype=torch.float)

print(np.round( A@B ,2)), print(' ')
# np.round( A@B.T ,2)
print(np.round(A@C1 ,2)), print(' ') # numpy and pytorch work here (sometimes they do smtimes don't)
print(np.round(A@C2 ,2))

tensor([[-1.9500, -1.4000, -0.7600, -1.1000,  0.5500],
        [ 0.4900, -0.0800,  1.5400, -3.1400, -2.0200],
        [ 0.5900,  1.9000, -2.6900, -2.9500, -6.2300]])
 
tensor([[-0.8300, -1.1000, -0.7800,  0.2200, -0.0400, -1.6400,  0.3100],
        [ 3.0100, -1.0000,  0.4600, -1.6200, -1.6600,  2.9200, -0.8500],
        [ 8.2900,  0.1400, -3.3200, -0.2200,  6.6300,  4.1400,  0.2300]],
       dtype=torch.float64)
 
tensor([[-0.8300, -1.1000, -0.7800,  0.2200, -0.0400, -1.6400,  0.3100],
        [ 3.0100, -1.0000,  0.4600, -1.6200, -1.6600,  2.9200, -0.8500],
        [ 8.2900,  0.1400, -3.3200, -0.2200,  6.6300,  4.1400,  0.2300]])
