In [ ]:
import numpy as np
import torch

In [ ]:
# generate a few random numbers
np.random.randn(5)

array([ 0.79838833,  0.09487156, -0.15280323, -0.93836674, -0.08865107])

In [ ]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17) # arbitaryb number
print(np.random.randn(5))
print(np.random.randn(5))
# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


New seed mechanism in numpy

In [ ]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print( randseed1.randn(5) ) # same seq.
print( randseed2.randn(5) ) # different from above, but same each time
print( randseed1.randn(5) ) # same as two up
print( randseed2.randn(5) ) # same as two up
print( np.random.randn(5) ) # different each time


[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.86962384  0.56778309  0.46528234 -1.16537308 -2.03599479]


In [ ]:

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 0.97754176 -0.13858525  0.10385631  0.30059104  0.9682053 ]

In [ ]:
torch.manual_seed(17)
print( torch.randn(5) )

# torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 1.1191818  -0.98339611  0.24452002 -0.58140974  0.4295639 ]
